# Generated by Django 3.1.2 on 2020-10-04 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=100)),
                ('Lastname', models.CharField(max_length=100)),
                ('Username', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('PasswordHash', models.CharField(max_length=500)),
                ('Jwt', models.CharField(max_length=100)),
                ('CreateDateTime', models.DateTimeField(auto_now_add=True)),
                ('LastUpdateDateTime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StaffId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Portal.person')),
            ],
        ),
    ]
