# Generated by Django 3.1.2 on 2020-10-04 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='StaffId',
            new_name='Staff',
        ),
    ]
